export default {
  back: require("../img/back-black.png"),
  "back-white": require("../img/back-white.png"),
  biceps: require("../img/biceps-black.png"),
  "biceps-white": require("../img/biceps-white.png"),
  chest: require("../img/chest-black.png"),
  "chest-white": require("../img/chest-white.png"),
  triceps: require("../img/triceps-black.png"),
  "triceps-white": require("../img/triceps-white.png"),
  shoulder: require("../img/shoulder-black.png"),
  "shoulder-white": require("../img/shoulder-white.png"),
  belly: require("../img/belly-black.png"),
  "belly-white": require("../img/belly-white.png"),
  legs: require("../img/legs-black.png"),
  "legs-white": require("../img/legs-white.png"),
  reset: require("../img/reset.png"),
  "reset-white": require("../img/reset-white.png"),
  completed: require("../img/completed-black.png"),
  "completed-white": require("../img/completed-white.png"),
  edit: require("../img/edit.png"),
  weight: require("../img/weight.png"),
  reps: require("../img/reps.png"),
  sets: require("../img/sets.png"),
  plus: require("../img/plus.png"),
  "plus-white": require("../img/plus-white.png"),
  minus: require("../img/minus.png"),
  hantel: require("../img/hantel.png")
}
